#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x30A59377A7763BE6 (slouken@libsdl.org)
#
Name     : SDL2_mixer
Version  : 2.0.2
Release  : 7
URL      : https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.tar.gz
Source99 : https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.tar.gz.sig
Summary  : Vorbis Library Development
Group    : Development/Tools
License  : Artistic-1.0-Perl BSD-3-Clause GFDL-1.2 GPL-2.0 LGPL-2.1 Zlib
Requires: SDL2_mixer-lib
BuildRequires : SDL2-dev
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(vorbisfile)

%description
This is a console based decoder/player for mono/stereo mpeg audio files,
probably more familiar as MP3 or MP2 files. It's focus is speed.
It can play MPEG1.0/2.0/2.5 layer I, II, II (1, 2, 3;-) files
(VBR files are fine, too) and produce output on a number of different ways:
raw data to stdout and different sound systems depending on your platform.

%package dev
Summary: dev components for the SDL2_mixer package.
Group: Development
Requires: SDL2_mixer-lib
Provides: SDL2_mixer-devel

%description dev
dev components for the SDL2_mixer package.


%package lib
Summary: lib components for the SDL2_mixer package.
Group: Libraries

%description lib
lib components for the SDL2_mixer package.


%prep
%setup -q -n SDL2_mixer-2.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1508859685
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1508859685
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL2/SDL_mixer.h
/usr/lib64/libSDL2_mixer.so
/usr/lib64/pkgconfig/SDL2_mixer.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL2_mixer-2.0.so.0
/usr/lib64/libSDL2_mixer-2.0.so.0.2.0
