#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 542402611043
#
# Source0 file verified with key 0x30A59377A7763BE6 (slouken@libsdl.org)
#
Name     : SDL2_mixer
Version  : 2.8.0
Release  : 24
URL      : https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.8.0.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.8.0.tar.gz
Source1  : https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.8.0.tar.gz.sig
Source2  : 30A59377A7763BE6.pkey
Summary  : Simple DirectMedia Layer - Sample Mixer Library
Group    : Development/Tools
License  : Artistic-1.0-Perl BSD-3-Clause LGPL-2.1 MIT Zlib
Requires: SDL2_mixer-lib = %{version}-%{release}
Requires: SDL2_mixer-license = %{version}-%{release}
BuildRequires : SDL2-dev
BuildRequires : buildreq-configure
BuildRequires : flac-dev
BuildRequires : gnupg
BuildRequires : libmodplug-dev
BuildRequires : mpg123-dev
BuildRequires : opus-dev
BuildRequires : opusfile-dev
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(fluidsynth)
BuildRequires : pkgconfig(libgme)
BuildRequires : pkgconfig(libmpg123)
BuildRequires : pkgconfig(opusfile)
BuildRequires : pkgconfig(vorbisfile)
BuildRequires : pkgconfig(wavpack)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Due to popular demand, here is a simple multi-channel audio mixer.
It supports 4 channels of 16 bit stereo audio, plus a single channel
of music, mixed by the popular ModPlug, Timidity MIDI, Ogg Vorbis,
Tremor, and libmpg123 MP3 libraries.

%package dev
Summary: dev components for the SDL2_mixer package.
Group: Development
Requires: SDL2_mixer-lib = %{version}-%{release}
Provides: SDL2_mixer-devel = %{version}-%{release}
Requires: SDL2_mixer = %{version}-%{release}

%description dev
dev components for the SDL2_mixer package.


%package lib
Summary: lib components for the SDL2_mixer package.
Group: Libraries
Requires: SDL2_mixer-license = %{version}-%{release}

%description lib
lib components for the SDL2_mixer package.


%package license
Summary: license components for the SDL2_mixer package.
Group: Default

%description license
license components for the SDL2_mixer package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 30A59377A7763BE6' gpg.status
%setup -q -n SDL2_mixer-2.8.0
cd %{_builddir}/SDL2_mixer-2.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732132089
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --enable-music-mod-modplug
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1732132089
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL2_mixer
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x64/LICENSE.gme.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/a1b087217d26810acdf85a9db199e8f3605b743a || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x64/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/881150ae67adeb2b26f8548a763b013330e06bad || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x64/LICENSE.opus.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/0ee22bb620ea5d6f60c54ea5b209e25b7f1e00ed || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x64/LICENSE.opusfile.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/e7e8faf55b60ce06e7ace3cbd3d6fb75f97bcb62 || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x64/LICENSE.wavpack.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/68c53d5ed22f12184a35615e44c0b0a780c3ee36 || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x64/LICENSE.xmp.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/23042ac3ce1baf0776488c351fcdeb02201e3d75 || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x86/LICENSE.gme.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/a1b087217d26810acdf85a9db199e8f3605b743a || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x86/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/881150ae67adeb2b26f8548a763b013330e06bad || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x86/LICENSE.opus.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/0ee22bb620ea5d6f60c54ea5b209e25b7f1e00ed || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x86/LICENSE.opusfile.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/e7e8faf55b60ce06e7ace3cbd3d6fb75f97bcb62 || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x86/LICENSE.wavpack.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/68c53d5ed22f12184a35615e44c0b0a780c3ee36 || :
cp %{_builddir}/SDL2_mixer-%{version}/VisualC/external/optional/x86/LICENSE.xmp.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/23042ac3ce1baf0776488c351fcdeb02201e3d75 || :
cp %{_builddir}/SDL2_mixer-%{version}/Xcode/iOS/SDL2.framework/License.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/56855624d497345923d749f17502a18029d72631 || :
cp %{_builddir}/SDL2_mixer-%{version}/Xcode/macOS/SDL2.framework/Versions/A/Resources/License.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/56855624d497345923d749f17502a18029d72631 || :
cp %{_builddir}/SDL2_mixer-%{version}/Xcode/tvOS/SDL2.framework/License.txt %{buildroot}/usr/share/package-licenses/SDL2_mixer/56855624d497345923d749f17502a18029d72631 || :
cp %{_builddir}/SDL2_mixer-%{version}/src/codecs/timidity/COPYING %{buildroot}/usr/share/package-licenses/SDL2_mixer/73cf7f25e9333afd31ef83960d2e0c94e986f3c5 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL2/SDL_mixer.h
/usr/lib64/cmake/SDL2_mixer/sdl2_mixer-config-version.cmake
/usr/lib64/cmake/SDL2_mixer/sdl2_mixer-config.cmake
/usr/lib64/libSDL2_mixer.so
/usr/lib64/pkgconfig/SDL2_mixer.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL2_mixer-2.0.so.0
/usr/lib64/libSDL2_mixer-2.0.so.0.800.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL2_mixer/0ee22bb620ea5d6f60c54ea5b209e25b7f1e00ed
/usr/share/package-licenses/SDL2_mixer/23042ac3ce1baf0776488c351fcdeb02201e3d75
/usr/share/package-licenses/SDL2_mixer/56855624d497345923d749f17502a18029d72631
/usr/share/package-licenses/SDL2_mixer/68c53d5ed22f12184a35615e44c0b0a780c3ee36
/usr/share/package-licenses/SDL2_mixer/73cf7f25e9333afd31ef83960d2e0c94e986f3c5
/usr/share/package-licenses/SDL2_mixer/881150ae67adeb2b26f8548a763b013330e06bad
/usr/share/package-licenses/SDL2_mixer/a1b087217d26810acdf85a9db199e8f3605b743a
/usr/share/package-licenses/SDL2_mixer/e7e8faf55b60ce06e7ace3cbd3d6fb75f97bcb62
